# Generated by Django 5.1.3 on 2025-02-07 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_stripe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sequential_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
